CREATE TABLE FILMES (
 ID_FILME SERIAL,
 TITULO VARCHAR(55) NOT NULL,
 DATA_LANCAMENTO DATE NOT NULL,
 NOTA INTEGER NOT NULL,
 DESCRICAO VARCHAR(55) NOT NULL,
 QUANTIDADE INTEGER NOT NULL
);

